name: CI
on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazel-contrib/setup-bazel@0.8.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - run: bazel build //...
      - run: bazel test //...
